{{ config(materialized='incremental', unique_key='surrogate_key') }}

  SELECT
    SHA1(CONCAT(location_key, date, aggregation_level)) AS surrogate_key,
    date,
    subregion2_code,
    subregion2_name,
    subregion1_code,
    subregion1_name,
    country_code,
    country_name,
    population,
    population_male,
    population_female,
    population_density,
    human_development_index,
    gdp_usd,
    gdp_per_capita_usd,
    openstreetmap_id,
    latitude,
    longitude,
    location_geometry,
    area_sq_km,
    hospital_beds_per_1000,
    aggregation_level,
    new_confirmed,
    new_deceased,
    new_persons_vaccinated,
    new_persons_fully_vaccinated,
    new_vaccine_doses_administered,
    new_tested,
    new_recovered,
    new_hospitalized_patients,
    new_intensive_care_patients,
    new_confirmed_male,
    new_confirmed_female,
    new_deceased_male,
    new_deceased_female,
    new_tested_male,
    new_tested_female,
    new_hospitalized_patients_male,
    new_hospitalized_patients_female,
    new_intensive_care_patients_male,
    new_intensive_care_patients_female,
    new_recovered_male,
    new_recovered_female,
    new_ventilator_patients,
    new_persons_fully_vaccinated_pfizer,
    new_vaccine_doses_administered_pfizer,
    new_persons_fully_vaccinated_moderna,
    new_vaccine_doses_administered_moderna,
    new_persons_fully_vaccinated_janssen,
    new_vaccine_doses_administered_janssen,
    current_hospitalized_patients,
    current_intensive_care_patients,
    current_ventilator_patients,
    school_closing,
    workplace_closing,
    cancel_public_events,
    restrictions_on_gatherings,
    public_transport_closing,
    stay_at_home_requirements,
    restrictions_on_internal_movement,
    international_travel_controls,
    income_support,
    debt_relief,
    fiscal_measures,
    international_support,
    public_information_campaigns,
    testing_policy,
    contact_tracing,
    emergency_investment_in_healthcare,
    investment_in_vaccines,
    facial_coverings,
    vaccination_policy,
    stringency_index,
    average_temperature_celsius,
    minimum_temperature_celsius,
    maximum_temperature_celsius
  FROM {{ source('covid19_open_data', 'covid19_open_data') }}
  WHERE subregion1_code = 'IA'
    AND country_code = 'US'
    AND date >= '{{ env_var("START_DATE", "") }}'
    AND date < '{{ env_var("END_DATE", "") }}'
